version: '{build}-alpha'
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
install:
- cmd: >-
    dnvm update-self

    dnvm install 1.0.0-beta8 -alias beta8

    dnvm use beta8
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dnu restore

    SET DNX_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- cmd: >-
    dnx -p tests\Component.Tests\ test

    dnx -p tests\EventStream.Tests\ test